[package]
name = "nom-mpq"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A nom parser for the MoPaQ archive format"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
thiserror = "1.0.38"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
compress = "0.2"
bzip2 = "0.4"
clap = { version = "4.1", features = ["derive"] }
serde_json = "1.0.91"
convert_case = "0.6.0"


[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
